import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

import "../globals.css";
import Footer from "./Footer";
import NavBar from "./NavBar";

const vazirmatn = Vazirmatn({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
          <NavBar />
          <main className="p-6">{children}</main>
          <Footer />
    </>
  );
}
