import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

import "../globals.css";
import Footer from "./Footer";
import NavBar from "./NavBar";
import HeaderContent from "./HeaderContent";

const vazirmatn = Vazirmatn({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavBar />
      <HeaderContent />
      <main className="md:p-6 container mx-auto">{children}</main>
      <Footer />
    </>
  );
}
