import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const vazirmatn = Vazirmatn({
  subsets : ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      className={cn(
        "h-full",
        "antialiased",
        vazirmatn.className
      )}
      dir="rtl"
    >
      <body className='min-h-full flex flex-col'>
        <main>{children}</main>
      </body>
    </html>
  );
}
