import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { Metadata } from "next";
import { ReactNode } from "react";
import "../globals.css";
import { AppSidebar } from "./admin/appSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Toaster />
      <SidebarProvider>
        <AppSidebar />
        <section className="w-full p-4">
          <main className="size-full bg-white">
            <section className="size-full bg-[#f6f6f8] rounded-2xl p-10">
              <SidebarTrigger variant='outline' className="cursor-pointer" />
              {children}
            </section>
          </main>
        </section>
      </SidebarProvider>
    </>
  );
};

export default RootLayout;
