import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { ReactNode } from "react";
import "../globals.css";
import { AppSidebar } from "./admin/appSidebar";

const vazirmatn = Vazirmatn({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Toaster />
      <SidebarProvider>
        <AppSidebar />
        <SidebarTrigger className="cursor-pointer" />
        <main className="h-screen w-screen flex justify-center items-center">
          {children}
        </main>
      </SidebarProvider>
    </>
  );
};

export default RootLayout;
